### ISSUE TITLE
Keeps making Redis connections

### ISSUE THREAD

**Issue by Slaventsiy** [taskforcesh/taskforce-connector#2]
The number of connections to Redis keeps growing over time and the connections are not closed.

**Comment by IvanMMM** [comment]
Met this some time ago, can confirm.

**Comment by manast** [comment]
There is a new taskforce-connector release (v1.1.1) that is closing one connection that was not closed properly before, would you mind to test with this one to see if the issue is resolved?

**Comment by manast** [comment]
Will close due to lack of feedback.
