### ISSUE TITLE
able to connect to only specified queues

### ISSUE THREAD

**Issue by UzalKhadka** [taskforcesh/taskforce-connector#54]
During the connection, the connector automatically connects to all the queues in the redis db unlike the other monitoring libraries like bull-board where you need to specify the Queue names. This has resulted the older queues (not required to be shown in the UI dashboard) to be included in the dashboard.
If there is a way to fix this can you please tell me the way?

**Comment by manast** [comment]
Currently, it is not possible to filter out any queues from the connection. But if the queues are old and irrelevant, why not delete them? you can also use a different database for newer queues, in Redis you can have up to 16 databases per instance. https://stackoverflow.com/questions/13386053/how-do-i-change-between-redis-database

**Comment by UzalKhadka** [comment]
Got it. I was using the same redis DB for multiple projects, and the additional queues from the other project were added during the Taskforce connection. Thanks @manast   for the quick response.
