### ISSUE TITLE
How do we set the user used to connect to redis?

### ISSUE THREAD

**Issue by bhoudu** [taskforcesh/taskforce-connector#6]
All the other parameters are editable, but we can't specify the username. We need to do that in order to connect to heroku redis as username can change (and we can't decide its value). Is there a way to achieve that?

**Comment by manast** [comment]
Redis does not require username in order to access to it, only an optional password. If you follow the steps in Heroku (https://devcenter.heroku.com/articles/heroku-redis#external-connections) does the resulting connection string include a username?

**Comment by bhoudu** [comment]
I have an URL like that:
redis://h:XXXXXXXX@ec2-XX-XX-XXX-XXX.eu-west-1.compute.amazonaws.com:XXXXX
It seems indeed I need to specify an user (here is 'h').

**Comment by manast** [comment]
I think that user is ignored by redis, it is just specified so that the connection string conforms with the uri specification.

**Comment by bhoudu** [comment]
Ok it seems it is completely ignored, my bad. It is working fine :)
